name: cobacli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  avatar_glow: 2.0.2
  cloud_firestore: ^3.1.8
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: 1.1.1
  firebase_auth: 3.3.6
  firebase_core: 1.12.0
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: 2.0.3
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  introduction_screen: 2.1.0
  lottie: 1.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
  uses-material-design: true
